export type catalogTypes = {
  index?: number,
  keyWorld?: string,
  imageMobile?: string,
  imageDesktop?: string,
  titleRu?: string,
  titleEn?: string,
  date?: string,
  long?: boolean,
  images?: object,
  bigImage?: string,
  descriptionRu?: object,
  descriptionEn?: object,
  open?: boolean,
}
